### PR TITLE
fixes to previous PR

### PR DESCRIPTION
**Pull request by lambrojos**
I did leave a couple of typos, plus forgot to bump version number
sorry

### CODE REVIEW

**Comment by molekilla** [comment]
Can we bump to hapi 12 or 13? or is it overkill ?

**Comment by lambrojos** [comment]
Sorry I think I did not understand... why should we require hapi 12.*/ 13.* while we know it works with hapi >=9.2.* ?

Or maybe you prefer to enforce a stricter dependency with something like this?
`  "peerDependencies": {
    "hapi": "^9.0.1 || ^10.0.0 || ^11.0.0 || ^12.0.0"
  },`

**Comment by molekilla** [comment]
yes, you're right, I already merged. Thanks again

**Comment by lambrojos** [comment]
Ok thank you for your patience :)
Will you be releasing on npm ?

**Comment by molekilla** [comment]
if it helps you, then expect that soon

**Comment by molekilla** [comment]
fyi, https://www.npmjs.com/package/hapi-passport-saml updated

**Pull request merged**
