### PR TITLE
Makes it compatible with Hapi 17

### LINKED ISSUE #9: Upgrade to hapi 17
Will this plugin support hapi 17?

### PR DESCRIPTION
**Pull request by JbIPS**
Modifies the `reply` system to make it compliant with Hapi 17

* Bumps Hapi types
* Uses latest version of passport-saml

Closes #9

### CODE REVIEW

**Comment by JbIPS** [comment]
I made it work with my Hapi 17 server and ADFS as IdP but some branches were never run in this scenario (I'm not sure of their purpose) so if someone could validate it against a different usecase that would be great :smiley:

**Comment by molekilla** [comment]
Can you bump to 2.0.0 and update readme / docs. Thanks.

**Comment by JbIPS** [comment]
All done :smiley:

**Comment by molekilla** [comment]
Looks good. If you get time, add some tests to it. Will merge later this week.

Thanks
Rogelio

**Comment by JbIPS** [comment]
Hello,

Sorry I've been a bit busy these days. What kind (and how) of tests shoul I had? It seems to me it's hard to test the behavior without and IdP but maybe you have a solution :smiley: 

Thank you

**Comment by JbIPS** [comment]
Hello again ! 

Do you have any ETA for this fix on NPM ? Thanks

**Comment by molekilla** [comment]
Later today.  Thanks

**Comment by molekilla** [comment]
done

**Comment by sscarduzio** [comment]
@JbIPS could you please update also the README.md? I'm clueless on how to use your new API :(

**Comment by JbIPS** [comment]
I'm not sure of what you're talking about, this is the standard Hapi API ([server.register](https://hapijs.com/api#server.register()))

**Comment by sscarduzio** [comment]
The issue I have is this: https://github.com/molekilla/hapi-passport-saml/issues/19

**Pull request merged**
