### PR TITLE
Use RelaySate

### PR DESCRIPTION
**Pull request by gdelpu**
SchemeAuthenticate modified to leverage RelaySate usage instead of Cookie to pass back to SP the url of the requested resource. This is mainly to address cumbersome behaviour of set-cookie during redirect (302) response, where the cookie is not added to the response.

### CODE REVIEW

**Comment by molekilla** [comment]
can you bump version and a ticket for me to push to npm, thanks.

**Comment by gdelpu** [comment]
@molekilla  HI, Version bumped, but I didn't get what you expect regarding "a ticket"

**Comment by Grogs** [comment]
Hello there! We just started using this plugin in our app at work, and it seems this change isn't working as intended. From my understanding, `RelaySate` in SchemeAuthenticate is a typo and should actually be `RelayState`?

**Comment by gdelpu** [comment]
@Grogs @molekilla You're right, I submit a new pull request  #26  to solve the issue. I'll work on implementing unit tests to avoid such situation in the future.

**Pull request merged**
